// <auto-generated />
using System;
using BudgetApp.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApp.Persistance.Migrations
{
    [DbContext(typeof(BudgetAppDbContext))]
    [Migration("20220908213539_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BudgetApp.Domain.Entities.CompanyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a92cb919-f6a7-450c-be8a-6fd91cc145ac"),
                            Description = "Commerce over Internet",
                            Name = "ECommerce"
                        },
                        new
                        {
                            Id = new Guid("e85db234-14ca-4cb7-9ac9-98350b3fd20a"),
                            Description = "Car and motorcycle repair",
                            Name = "Mechanics"
                        },
                        new
                        {
                            Id = new Guid("74ffba7c-dcfa-413f-ae55-5afda06863a7"),
                            Description = "Scientific research",
                            Name = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
